mandatoryAccounts:
  - name: Management
    description: >-
      Compte de gestion (racine de l'organisation). Ne PAS changer le nom de ce compte.
      Le nom effectif du compte AWS n'a pas besoin de correspondre au nom dans cette configuration.
    email: <Management>@example.com  <----- UPDATE EMAIL ADDRESS
    organizationalUnit: Root
    warm: false
  - name: LogArchive
    description: >-
      Compte d'archive de journaux. Ne PAS changer le nom de ce compte.
      Le nom effectif du compte AWS n'a pas besoin de correspondre au nom dans cette configuration.
    email: <LogArchive>@example.com  <----- UPDATE EMAIL ADDRESS
    organizationalUnit: Security
    warm: false
  - name: Audit
    description: >-
      Compte de sécurité. Ne PAS changer le nom de ce compte.
      Le nom effectif du compte AWS n'a pas besoin de correspondre au nom dans cette configuration.
    email: <Audit>@example.com  <----- UPDATE EMAIL ADDRESS
    organizationalUnit: Security
    warm: false
workloadAccounts: 
  - name: SharedServices
    description: >-
      Compte pour les services partagés dans toute l'organisation. Ne PAS changer le nom de ce compte.
      Le nom effectif du compte AWS n'a pas besoin de correspondre au nom dans cette configuration.
    email: <shared-services>@example.com  <----- UPDATE EMAIL ADDRESS
    organizationalUnit: Infrastructure
  - name: Network
    description: >-
      Compte pour la réseautique centralisée dans toute l'organisation. Ne PAS changer le nom de ce compte.
      Le nom effectif du compte AWS n'a pas besoin de correspondre au nom dans cette configuration.
    email: <Network>@example.com  <----- UPDATE EMAIL ADDRESS
    organizationalUnit: Infrastructure
  - name:  ProductionWorkloads
    description: >-
      (PRODUCTION) Compte pour les charges de travail de production.
      Le nom effectif du compte AWS n'a pas besoin de correspondre au nom dans cette configuration.
    email: <Production>@example.com  <----- UPDATE EMAIL ADDRESS
    organizationalUnit: Production
  - name:  RestrictedWorkloads
    description: >-
      (PRODUCTION) Compte pour les charges de travail comportant des renseignements sensibles (aucun accès Internet).
      Le nom effectif du compte AWS n'a pas besoin de correspondre au nom dans cette configuration.
    email: <Restricted>@example.com  <----- UPDATE EMAIL ADDRESS
    organizationalUnit: Restricted
  - name:  NonProductionWorkloads
    description: >-
      (NON-PRODUCTION) Compte pour les charges de travail en cours de développement.
      Le nom effectif du compte AWS n'a pas besoin de correspondre au nom dans cette configuration.
    email: <NonProd>@example.com  <----- UPDATE EMAIL ADDRESS
    organizationalUnit: NonProduction
